# Generated by Django 4.0.4 on 2022-09-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('discounted_price', models.IntegerField()),
                ('description', models.TextField()),
                ('overview', models.TextField()),
                ('price', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product/thumbnails')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
