# Generated by Django 4.0.4 on 2022-09-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_subcategory_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=22),
            preserve_default=False,
        ),
    ]
