# Generated by Django 4.0.4 on 2022-09-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, choices=[('featured', 'Featured'), ('', 'Default')], max_length=50),
        ),
    ]
