# Generated by Django 4.0.4 on 2022-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, choices=[('featured', 'Featured'), ('offer', 'Offer'), ('', 'Default')], max_length=50),
        ),
    ]
