# Generated by Django 4.0.4 on 2022-10-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_alter_vendor_created_at'),
        ('product', '0013_alter_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
