# Generated by Django 4.0.4 on 2022-09-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_category_alter_product_subcategory'),
        ('store', '0004_slider_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='image',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='rank',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
